{ src: 'plugin/pdfexport/pdfexport.js', async: true },
{ src: 'plugin/skip-fragments/skip-fragments.js' },
{ src: 'plugin/jump-plugin/jump/jump.js' },
{ src: 'plugin/elapsed-time-bar/plugin/elapsed-time-bar/elapsed-time-bar.js' },
{ src: 'plugin/mouse-pointer/mouse-pointer.js', async: true },
