= Asciidoctor ➟ Reveal.js pass:q[<br><span id="subtitle">] -- Demo Presentation -- pass:q[</span><br><br>]
René Wirnata <rene.wirnata@scandio.de>
2022-01-27
// -- asciidoc settings --
:experimental:
:icons: font
:stem: latexmath
:hide-uri-scheme:
:figure-caption!:
:source-highlighter: highlightjs
:highlightjs-languages: asciidoc
:customcss: custom.css
// -- reveal.js settings -- (see https://docs.asciidoctor.org/reveal.js-converter/latest/converter/revealjs-options/)
:revealjsdir: reveal.js
:revealjs_plugins: plugins.js
:revealjs_plugins_configuration: plugins-conf.js
// :revealjs_center: false
:revealjs_totalTime: 1800
:revealjs_transition: fade
:revealjs_transitionSpeed: slow
:revealjs_controls: false
:revealjs_navigationMode: linear
:revealjs_hash: true
:revealjs_fragmentInURL: true
:revealjs_slideNumber: c/t
// -- pdf export options --
:revealjs_pdfseparatefragments: false
:revealjs_pdfmaxpagesperslide: 1
// -- custom attributes -- (see https://discuss.asciidoctor.org/Getting-blank-lines-in-AsciiDoc-td47.html)
:blank: pass:[ +]
:vsp12: pass:[<p style="margin-bottom:0.50em; display:flex"></p>]
:vsp13: pass:[<p style="margin-bottom:0.33em; display:flex"></p>]
:vsp14: pass:[<p style="margin-bottom:0.25em; display:flex"></p>]
:hsp2: pass:a[{nbsp} {nbsp}]
:hsp3: pass:a[{nbsp} {nbsp} {nbsp}]
:hsp9: pass:a[{hsp3} {hsp3} {hsp3}]



== Customizations

Some Asciidoctor elements have been customized via CSS to
https://github.com/asciidoctor/asciidoctor-reveal.js/tree/master/examples


=== Admonitions

NOTE: This is a note.

{vsp14}

TIP: This is a tip.

{vsp14}

IMPORTANT: This is important.

{vsp14}

WARNING: This is a warning.

{vsp14}

CAUTION: Here you have to be cautious!





== Useful Plugins

In reveal.js v3.x
https://github.com/hakimel/reveal.js/wiki/Plugins,-Tools-and-Hardware[external plugins]
are configured in two files:


[source,linenums]
----
:revealjs_plugins: plugins.js <1>
:revealjs_plugins_configuration: plugins-conf.js <2>
----

{vsp12}

<1> includes all javascript plugin sources (loading)
<2> is used to set plugin options (configuration)

{vsp12}

[NOTE]
All plugins are included via `git submodules` and +
have been tested to work with this Reveal.js version.

{vsp12}



=== PDF Export

The https://github.com/McShelby/reveal-pdfexport[pdfexport plugin] simply
adds a shortcut for switching to PDF mode, i.e. adding `?print-pdf` to the base
URL.

---

*-- Loading --*

[source,javascript,linenums]
----
{ src: 'plugin/pdfexport.js', async: true }
----

*-- Configuration --*

[source,javascript,linenums]
----
pdfExportShortcut: 'E'
----



=== Skip Fragments (1)

The https://github.com/PiDayDev/reveal-skip-fragments[skip-fragments plugin]
adds shortcuts to \...

[%step]
* reveal `SkipFragments.showAll();` or
* hide `SkipFragments.hideAll();`

\... all fragments on a slide.

---

*-- Loading --*

[source,javascript,linenums]
----
{ src: 'plugin/skip-fragments/skip-fragments.js' }
----

*-- Configuration --*

[source,javascript,linenums]
----
/* Shortcut for showing all fragments */
skipFragmentsShowShortcut: 'V',
/* Shortcut for hiding all fragments */
skipFragmentsHideShortcut: 'C',
----



// NOTE: for kbd[] macro to render, :experimental: is required in the header
=== Skip Fragments (2)

This plugin is also used for a small script bound to +
kbd:[PgUp] and kbd:[PgDown], +
that enables you to skip through slides without +
having to reveal/hide every single fragment.

---

*-- Configuration --*

[source,javascript,linenums]
----
keyboard: {
  33: function() {
      let idx = Reveal.getIndices()
      let routes = Reveal.availableRoutes()
      if( routes.up ){
        Reveal.slide(idx.h, idx.v - 1);
      } else if( routes.left ){
        Reveal.slide(idx.h - 1);
      }
      SkipFragments.showAll()
    },
}
----



=== Jump to Slide

The https://github.com/SethosII/reveal.js-jump-plugin[jump-plugin] allows you
to easily switch to any slide using its kbd:[number] followed by kbd:[Enter].

For jumping to the M^th^ _vertical_ slide of the N^th^ _horizontal_ slide, use
the combination kbd:[N-M] + kbd:[Enter].

---

*-- Loading --*

[source,javascript,linenums]
----
{ src: 'plugin/jump-plugin/jump/jump.js' },
----



=== Elapsed Time Bar

The https://github.com/tkrkt/reveal.js-elapsed-time-bar[elapsed time bar]
plugin add a customizable progress bar at the bottom of the slide that tracks
your talk-time.

---

*-- Loading --*

[source,javascript,linenums]
----
{ src: 'plugin/jump-plugin/jump/jump.js' },
----

*-- Configuration --*

[source,js,linenums]
----
/* - (required) allotted time for presentation (30min) */
allottedTime: 30 * 60 * 1000,
/* - (optional) height of page/time progress bar */
progressBarHeight: 3,
/* - (optional) bar color */
barColor: 'rgb(200,0,0)',
/* - (optional) bar color when timer is paused */
pausedBarColor: 'rgba(200,0,0,.6)',
----



=== Mouse Pointer

The https://github.com/caiofcm/plugin-revealjs-mouse-pointer[mouse pointer]
plugin is triggered with kbd:[Shift] + kbd:[CAPSLOCK] and transforms your
cursor into a cirular red pointer.

{vsp12}

NOTE: This plugin cannot be customized and needs a proper re-write.

=== Verticator

The https://github.com/Martinomagnifico/reveal.js-verticator[verticator] plugin
adds small dots on the right of the +
slide indication progress in the vertical slide axis.

IMPORTANT: This plugin cannot be used as is, because the user is +
supposed to add a `<ul class='verticator'></ul>` tag +
right after the `<div class='reveal'>` tag.

---

*-- Fix --*

[source,js,linenums]
----
let reveal = document.getElementsByClassName("reveal")[0];
let verticator = document.createElement("ul");
verticator.className = "verticator";
reveal.prepend(verticator);
----

*-- Loading --*

[source,js,linenums]
----
{ src: 'plugin/plugin_fixes.js' },
{ src: 'plugin/.../verticator.js' },
----





== Code

[source,java,linenums,highlight='1..9|2..4|6..8']
----
public class TestClass { // <1>
    public TestClass() {

    }

    public void testMethod() {

    }
}
----

<1> test 123
